### ISSUE TITLE
Typo in the hacktoberfest label

### ISSUE THREAD

**Issue by rmnbrgr** [Just-A-Visitor/Algorithmic-Pseudocode#119]
You labeled this repo with _hactoberfest_ instead of _hacktoberfest_. Could you please fix that so that PRs in this repo count?

**Comment by Just-A-Visitor** [comment]
Ah, that was a mistake on my part. I've deleted the invalid. On the flip-side, the correct label `hacktoberfest` was already added to this repo (and still is). 

P.S : In case you are talking about the `repo-topic` and not `issue-label`, I've fixed that too.
