### ISSUE TITLE
Implement a PDF explanation for Bubble Sort Pseudocode

### ISSUE THREAD

**Issue by ardasengun04** [Just-A-Visitor/Algorithmic-Pseudocode#129]
I want to explain tor the bubble search algorithm in the pseudocode folder with images and animations.

**Comment by Just-A-Visitor** [comment]
Sure, go ahead. Let me know if you need any help.

**Comment by TheProgrammerGod** [comment]
Hey @Just-A-Visitor , is the other guy still working on the issue ? If not , could you assign me to work on it?

**Comment by Just-A-Visitor** [comment]
@TheProgrammerGod  Apparently not. Yes, you can start working on it.

**Comment by TheProgrammerGod** [comment]
Alright I'll start working on it right away.

**Comment by TheProgrammerGod** [comment]
I have added the pdf file. Check it once and let me know if it requires any edits. I'd also like to contribute by writing explanations for selection sort , insertion sort, linear search and binary search if needed.

**Comment by TheProgrammerGod** [comment]
@Just-A-Visitor hey buddy , could you label my pr with some Hacktober fest label or something? I'm participating

**Comment by Just-A-Visitor** [comment]
@TheProgrammerGod Sure, done.

**Comment by SterMoum** [comment]
@Just-A-Visitor Hello. I am happy to help if the issue hasn't been resolved

**Comment by Just-A-Visitor** [comment]
@Stergios13  IIRC, this issue has been resolved. Closing it now.
