### ISSUE TITLE
Pseudocode for Activity Selection

### ISSUE THREAD

**Issue by ghost** [Just-A-Visitor/Algorithmic-Pseudocode#13]

**Comment by pjzzz** [comment]
Hey, I would like to work on this issue. Also since there is no Greedy folder in Psuedocode I will need to make one or am I supposed to do something else?

**Comment by ghost** [comment]
Yes, You should put the file in the directory `Pseudocode/Greedy Algorithms/SourceCode.tex`. Remember **not** to include the `pdf` file
