### ISSUE TITLE
Pseudocode for Stock Span

### ISSUE THREAD

**Issue by ghost** [Just-A-Visitor/Algorithmic-Pseudocode#27]

**Comment by codeboy5** [comment]
Hi i would like to contribute to this

**Comment by ghost** [comment]
I've just posted the instructions in the mega thread. Please share your solution link before writing the pseudocode.

**Comment by codeboy5** [comment]
My solution := https://gist.github.com/codeboy5/b431918db08250933a08362b6731d36b

**Comment by ghost** [comment]
Looks good. You can start working on the pseudocode now. (Remember to use 1 Based indexing).

**Comment by ghost** [comment]
I think it can be made more concise by removing the part where you manually push the first index onto the stock. The line `If( s.empty()) then span[i] = i + 1` will take care of it.

**Comment by ghost** [comment]
#54
