### ISSUE TITLE
Pseudocode for Insertion Sort

### ISSUE THREAD

**Issue by ghost** [Just-A-Visitor/Algorithmic-Pseudocode#38]

**Comment by yildirimyigit** [comment]
Hello @Just-A-Visitor,

Would you like me to work on this one too? I have already implemented a the algorithm here: https://onlinegdb.com/BJhjHIDtB

**Comment by ghost** [comment]
Looks good. However, I prefer the **CLRS** version.

**Reason** : The worst case for insertion sort happens when the array is sorted in strictly decreasing order. However, on average, insertion sort performs better than merge sort on smaller inputs. This is because we don't need to cross over every element if a chunk of the array is already sorted. 

Ideally, Insertion sort should make `n` comparisons if the array is already sorted. However, in your code, it makes `n * (n+1) /2` comparisons, no matter what the input. (Can you see how?).

However, [this](https://ide.geeksforgeeks.org/f8LkA61epC) version from **CLRS** does the job in a minimal number of comparisons by avoiding unnecessary comparisons. Moreover, I find it quite intuitive because it does what it says, **Insert the `i-th` element in its correct position assuming everything to the left is already sorted**. Of course, the base case is that the first element is sorted.


I would suggest you to go and read the above code to see how things work (and hopefully learn something new in the process). After that, you can start writing the pseudocode. (Use 1 based indexing).[And please cite CLRS at the end of the pseudocode if you decide to go with this one!]

If you have any queries, you can ask in this thread.

**Comment by ghost** [comment]
You can validate your code [here](https://leetcode.com/problems/sort-an-array). (The verdict should be **TLE** and not WA).

**Comment by yildirimyigit** [comment]
Ok, I just wanted to quickly implement the algorithm as I remembered it, without thinking thoroughly. Anyways, **CRLS** is better, of course and I can see why. Thanks for the info, by the way.

Now I'm writing the pseudocode.

**Comment by yildirimyigit** [comment]
Where do you want me to put the `SourceCode.tex` for this one?

**Comment by ghost** [comment]
`Pseudocode/Sorting/Insertion Sort/SourceCode.tex`

**Comment by yildirimyigit** [comment]
https://github.com/Just-A-Visitor/Algorithmic-Pseudocode/pull/41
