### ISSUE TITLE
Pseudocode for Buying and Selling Stocks (No Restriction)

### ISSUE THREAD

**Issue by ghost** [Just-A-Visitor/Algorithmic-Pseudocode#44]
The second version on Leetcode (You can buy and sell any number of times).

**Comment by tataudat** [comment]
Is there anyone working on this? I would like to have a take on this one.

**Comment by lepasq** [comment]
Hi! I'd like to contribute to your repository and created a .tex file for this Leetcode problem. I'd love to get some feedback!

[main.pdf](https://github.com/Just-A-Visitor/Algorithmic-Pseudocode/files/4374938/main.pdf)

**Comment by ghost** [comment]
Hi. Sorry for the delayed response.

1) I would generally prefer one based indexing in pseudocodes.
2) Can you make `in` boldface?
3) If possible, can you include a short explanation at the end?

Thanks

**Comment by lepasq** [comment]
> Hi. Sorry for the delayed response.
> 
>     1. I would generally prefer one based indexing in pseudocodes.
> 
>     2. Can you make `in` boldface?
> 
>     3. If possible, can you include a short explanation at the end?
> 
> 
> Thanks

Thank you for your feedback.

I applied the suggested changes and added a small walkthrough. What do you think about it?
[main_version 2.pdf](https://github.com/Just-A-Visitor/Algorithmic-Pseudocode/files/4403198/main_version.2.pdf)

**Comment by ghost** [comment]
Looks good. A minor point, `for i = 1` **to** `len-1`.

Also, it's better to post the TEX code so that the repository size isn't unnecessarily increased. (I can anyway generate them from my side).

Please make a pull request for the same (following the naming conventions).
