### ISSUE TITLE
Small Typo :)

### ISSUE THREAD

**Issue by pjzzz** [Just-A-Visitor/Algorithmic-Pseudocode#52]
https://github.com/Just-A-Visitor/Algorithmic-Pseudocode/blob/ce080e9c798a2d928990575206faccc33b3f7a7f/Pseudocode/Dynamic%20Programming/Longest%20Common%20Subsequence/SourceCode.tex#L24

There is a typo _comomon_ should be _common_ .

**Comment by ghost** [comment]
Thanks. I'll rectify this in the new commit.
